node{
    def Image=""
   
    stage('Code Checout'){
        git 'https://github.com/BalajiSriram1995/DevOps_Bootcamp.git'
    }

    stage('Code Build using Maven'){
        def mvnHome = tool 'maven3'
def mavenCMD="${mvnHome}/bin/mvn"
        sh "cd cicd-pipeline && ${mavenCMD} clean package"
    }

    stage('Create Docker Image'){
        //sh "cd cicd-pipeline && docker build -t balajisriram1995/docker-sb ."
Image = docker.build("balajisriram1995/docker-sb","./cicd-pipeline")
}
       
    stage('Push Docker Image'){
        withDockerRegistry(credentialsId: 'DockerCred', toolName: 'docker') {
Image.push()
}
    }
   
    stage('Deploy to Cloud Foundry'){
       
        def url="https://api.run.pivotal.io"
        def org="Balaji1995"
        def spc="development"
       
        withCredentials([usernamePassword(credentialsId: 'pcfcred', passwordVariable: 'pwd', usernameVariable: 'user')]) {
       
        sh "cf login -a ${url} -u ${user} -p ${pwd} -o ${org} -s ${spc}"

        }
       
        sh "cf push mypcfdockerapp01 --docker-image balajisriram1995/docker-sb"

    }
 
  }